// gen-locales.cjs — 12 locales for the character-showcase app. Norwegian default.
// WoW terms (Mythic+, raid, ilvl) kept as recognised game terms across langs.
const fs = require("fs"); const path = require("path");
const LANGS = ["no","en","nl","fr","de","it","sv","da","fi","es","pl","pt"];
const OUT = path.join(__dirname, "src", "i18n", "locales");
fs.mkdirSync(OUT, { recursive: true });

const S = {
  no:{appName:"Wartable",tagline:"Vis frem karakteren din.",signIn:"Logg inn",continueBattleNet:"Fortsett med Battle.net",continueManual:"Fortsett uten innlogging",pickCharacter:"Velg karakter",myCharacters:"Mine karakterer",lookup:"Søk opp",enterCharacter:"Karakternavn",realm:"Realm",region:"Region",search:"Søk",gear:"Utstyr",mythicPlus:"Mythic+",raids:"Raid",achievements:"Prestasjoner",itemLevel:"Gjenstandsnivå",rating:"Vurdering",bestRuns:"Beste løp",noRuns:"Ingen løp denne sesongen",guild:"Laug",share:"Del",shareCode:"Delingskode",createCode:"Lag delingskode",viewCode:"Vis en kode",enterCode:"Skriv inn kode",myCodes:"Mine koder",copied:"Kopiert",settings:"Innstillinger",language:"Språk",theme:"Tema",themeLight:"Lyst",themeDark:"Mørkt",themeSystem:"System",signOut:"Logg ut",loading:"Laster …",retry:"Prøv igjen",notFound:"Ikke funnet",noChars:"Ingen karakterer. Logg inn med Battle.net.",level:"Nivå"},
  en:{appName:"Wartable",tagline:"Show off your character.",signIn:"Sign in",continueBattleNet:"Continue with Battle.net",continueManual:"Continue without sign-in",pickCharacter:"Pick a character",myCharacters:"My characters",lookup:"Look up",enterCharacter:"Character name",realm:"Realm",region:"Region",search:"Search",gear:"Gear",mythicPlus:"Mythic+",raids:"Raids",achievements:"Achievements",itemLevel:"Item level",rating:"Rating",bestRuns:"Best runs",noRuns:"No runs this season",guild:"Guild",share:"Share",shareCode:"Share code",createCode:"Create share code",viewCode:"View a code",enterCode:"Enter code",myCodes:"My codes",copied:"Copied",settings:"Settings",language:"Language",theme:"Theme",themeLight:"Light",themeDark:"Dark",themeSystem:"System",signOut:"Sign out",loading:"Loading …",retry:"Retry",notFound:"Not found",noChars:"No characters. Sign in with Battle.net.",level:"Level"},
  nl:{appName:"Wartable",tagline:"Toon je personage.",signIn:"Inloggen",continueBattleNet:"Doorgaan met Battle.net",continueManual:"Doorgaan zonder inloggen",pickCharacter:"Kies een personage",myCharacters:"Mijn personages",lookup:"Opzoeken",enterCharacter:"Personagenaam",realm:"Realm",region:"Regio",search:"Zoeken",gear:"Uitrusting",mythicPlus:"Mythic+",raids:"Raids",achievements:"Prestaties",itemLevel:"Itemniveau",rating:"Score",bestRuns:"Beste runs",noRuns:"Geen runs dit seizoen",guild:"Gilde",share:"Delen",shareCode:"Deelcode",createCode:"Deelcode maken",viewCode:"Code bekijken",enterCode:"Code invoeren",myCodes:"Mijn codes",copied:"Gekopieerd",settings:"Instellingen",language:"Taal",theme:"Thema",themeLight:"Licht",themeDark:"Donker",themeSystem:"Systeem",signOut:"Uitloggen",loading:"Laden …",retry:"Opnieuw",notFound:"Niet gevonden",noChars:"Geen personages. Log in met Battle.net.",level:"Niveau"},
  fr:{appName:"Wartable",tagline:"Mettez votre personnage en valeur.",signIn:"Se connecter",continueBattleNet:"Continuer avec Battle.net",continueManual:"Continuer sans connexion",pickCharacter:"Choisir un personnage",myCharacters:"Mes personnages",lookup:"Rechercher",enterCharacter:"Nom du personnage",realm:"Royaume",region:"Région",search:"Rechercher",gear:"Équipement",mythicPlus:"Mythique+",raids:"Raids",achievements:"Hauts faits",itemLevel:"Niveau d'objet",rating:"Cote",bestRuns:"Meilleures clés",noRuns:"Aucune clé cette saison",guild:"Guilde",share:"Partager",shareCode:"Code de partage",createCode:"Créer un code",viewCode:"Voir un code",enterCode:"Saisir le code",myCodes:"Mes codes",copied:"Copié",settings:"Paramètres",language:"Langue",theme:"Thème",themeLight:"Clair",themeDark:"Sombre",themeSystem:"Système",signOut:"Se déconnecter",loading:"Chargement …",retry:"Réessayer",notFound:"Introuvable",noChars:"Aucun personnage. Connectez-vous avec Battle.net.",level:"Niveau"},
  de:{appName:"Wartable",tagline:"Zeig deinen Charakter.",signIn:"Anmelden",continueBattleNet:"Mit Battle.net fortfahren",continueManual:"Ohne Anmeldung fortfahren",pickCharacter:"Charakter wählen",myCharacters:"Meine Charaktere",lookup:"Suchen",enterCharacter:"Charaktername",realm:"Realm",region:"Region",search:"Suchen",gear:"Ausrüstung",mythicPlus:"Mythisch+",raids:"Schlachtzüge",achievements:"Erfolge",itemLevel:"Gegenstandsstufe",rating:"Wertung",bestRuns:"Beste Läufe",noRuns:"Keine Läufe diese Saison",guild:"Gilde",share:"Teilen",shareCode:"Teilcode",createCode:"Teilcode erstellen",viewCode:"Code ansehen",enterCode:"Code eingeben",myCodes:"Meine Codes",copied:"Kopiert",settings:"Einstellungen",language:"Sprache",theme:"Design",themeLight:"Hell",themeDark:"Dunkel",themeSystem:"System",signOut:"Abmelden",loading:"Lädt …",retry:"Erneut",notFound:"Nicht gefunden",noChars:"Keine Charaktere. Mit Battle.net anmelden.",level:"Stufe"},
  it:{appName:"Wartable",tagline:"Mostra il tuo personaggio.",signIn:"Accedi",continueBattleNet:"Continua con Battle.net",continueManual:"Continua senza accesso",pickCharacter:"Scegli un personaggio",myCharacters:"I miei personaggi",lookup:"Cerca",enterCharacter:"Nome personaggio",realm:"Reame",region:"Regione",search:"Cerca",gear:"Equipaggiamento",mythicPlus:"Mitica+",raids:"Incursioni",achievements:"Imprese",itemLevel:"Livello oggetti",rating:"Punteggio",bestRuns:"Migliori run",noRuns:"Nessuna run questa stagione",guild:"Gilda",share:"Condividi",shareCode:"Codice",createCode:"Crea codice",viewCode:"Vedi un codice",enterCode:"Inserisci codice",myCodes:"I miei codici",copied:"Copiato",settings:"Impostazioni",language:"Lingua",theme:"Tema",themeLight:"Chiaro",themeDark:"Scuro",themeSystem:"Sistema",signOut:"Esci",loading:"Caricamento …",retry:"Riprova",notFound:"Non trovato",noChars:"Nessun personaggio. Accedi con Battle.net.",level:"Livello"},
  sv:{appName:"Wartable",tagline:"Visa upp din karaktär.",signIn:"Logga in",continueBattleNet:"Fortsätt med Battle.net",continueManual:"Fortsätt utan inloggning",pickCharacter:"Välj en karaktär",myCharacters:"Mina karaktärer",lookup:"Sök upp",enterCharacter:"Karaktärsnamn",realm:"Realm",region:"Region",search:"Sök",gear:"Utrustning",mythicPlus:"Mythic+",raids:"Raids",achievements:"Bedrifter",itemLevel:"Föremålsnivå",rating:"Betyg",bestRuns:"Bästa runs",noRuns:"Inga runs den här säsongen",guild:"Gille",share:"Dela",shareCode:"Delningskod",createCode:"Skapa delningskod",viewCode:"Visa en kod",enterCode:"Ange kod",myCodes:"Mina koder",copied:"Kopierad",settings:"Inställningar",language:"Språk",theme:"Tema",themeLight:"Ljust",themeDark:"Mörkt",themeSystem:"System",signOut:"Logga ut",loading:"Laddar …",retry:"Försök igen",notFound:"Hittades inte",noChars:"Inga karaktärer. Logga in med Battle.net.",level:"Nivå"},
  da:{appName:"Wartable",tagline:"Vis din karakter frem.",signIn:"Log ind",continueBattleNet:"Fortsæt med Battle.net",continueManual:"Fortsæt uden login",pickCharacter:"Vælg en karakter",myCharacters:"Mine karakterer",lookup:"Slå op",enterCharacter:"Karakternavn",realm:"Realm",region:"Region",search:"Søg",gear:"Udstyr",mythicPlus:"Mythic+",raids:"Raids",achievements:"Bedrifter",itemLevel:"Genstandsniveau",rating:"Vurdering",bestRuns:"Bedste runs",noRuns:"Ingen runs denne sæson",guild:"Laug",share:"Del",shareCode:"Delingskode",createCode:"Opret delingskode",viewCode:"Vis en kode",enterCode:"Indtast kode",myCodes:"Mine koder",copied:"Kopieret",settings:"Indstillinger",language:"Sprog",theme:"Tema",themeLight:"Lyst",themeDark:"Mørkt",themeSystem:"System",signOut:"Log ud",loading:"Indlæser …",retry:"Prøv igen",notFound:"Ikke fundet",noChars:"Ingen karakterer. Log ind med Battle.net.",level:"Niveau"},
  fi:{appName:"Wartable",tagline:"Esittele hahmosi.",signIn:"Kirjaudu",continueBattleNet:"Jatka Battle.netillä",continueManual:"Jatka ilman kirjautumista",pickCharacter:"Valitse hahmo",myCharacters:"Omat hahmot",lookup:"Hae",enterCharacter:"Hahmon nimi",realm:"Realm",region:"Alue",search:"Hae",gear:"Varusteet",mythicPlus:"Mythic+",raids:"Raidit",achievements:"Saavutukset",itemLevel:"Esinetaso",rating:"Pisteet",bestRuns:"Parhaat juoksut",noRuns:"Ei juoksuja tällä kaudella",guild:"Kilta",share:"Jaa",shareCode:"Jakokoodi",createCode:"Luo jakokoodi",viewCode:"Näytä koodi",enterCode:"Syötä koodi",myCodes:"Omat koodit",copied:"Kopioitu",settings:"Asetukset",language:"Kieli",theme:"Teema",themeLight:"Vaalea",themeDark:"Tumma",themeSystem:"Järjestelmä",signOut:"Kirjaudu ulos",loading:"Ladataan …",retry:"Yritä uudelleen",notFound:"Ei löytynyt",noChars:"Ei hahmoja. Kirjaudu Battle.netillä.",level:"Taso"},
  es:{appName:"Wartable",tagline:"Luce tu personaje.",signIn:"Iniciar sesión",continueBattleNet:"Continuar con Battle.net",continueManual:"Continuar sin iniciar sesión",pickCharacter:"Elige un personaje",myCharacters:"Mis personajes",lookup:"Buscar",enterCharacter:"Nombre del personaje",realm:"Reino",region:"Región",search:"Buscar",gear:"Equipo",mythicPlus:"Mítica+",raids:"Bandas",achievements:"Logros",itemLevel:"Nivel de objeto",rating:"Puntuación",bestRuns:"Mejores carreras",noRuns:"Sin carreras esta temporada",guild:"Hermandad",share:"Compartir",shareCode:"Código",createCode:"Crear código",viewCode:"Ver un código",enterCode:"Introducir código",myCodes:"Mis códigos",copied:"Copiado",settings:"Ajustes",language:"Idioma",theme:"Tema",themeLight:"Claro",themeDark:"Oscuro",themeSystem:"Sistema",signOut:"Cerrar sesión",loading:"Cargando …",retry:"Reintentar",notFound:"No encontrado",noChars:"Sin personajes. Inicia sesión con Battle.net.",level:"Nivel"},
  pl:{appName:"Wartable",tagline:"Pochwal się postacią.",signIn:"Zaloguj się",continueBattleNet:"Kontynuuj z Battle.net",continueManual:"Kontynuuj bez logowania",pickCharacter:"Wybierz postać",myCharacters:"Moje postacie",lookup:"Wyszukaj",enterCharacter:"Nazwa postaci",realm:"Realm",region:"Region",search:"Szukaj",gear:"Ekwipunek",mythicPlus:"Mityczna+",raids:"Rajdy",achievements:"Osiągnięcia",itemLevel:"Poziom przedmiotu",rating:"Wynik",bestRuns:"Najlepsze biegi",noRuns:"Brak biegów w tym sezonie",guild:"Gildia",share:"Udostępnij",shareCode:"Kod",createCode:"Utwórz kod",viewCode:"Zobacz kod",enterCode:"Wpisz kod",myCodes:"Moje kody",copied:"Skopiowano",settings:"Ustawienia",language:"Język",theme:"Motyw",themeLight:"Jasny",themeDark:"Ciemny",themeSystem:"Systemowy",signOut:"Wyloguj się",loading:"Ładowanie …",retry:"Ponów",notFound:"Nie znaleziono",noChars:"Brak postaci. Zaloguj się przez Battle.net.",level:"Poziom"},
  pt:{appName:"Wartable",tagline:"Mostra a tua personagem.",signIn:"Entrar",continueBattleNet:"Continuar com Battle.net",continueManual:"Continuar sem iniciar sessão",pickCharacter:"Escolhe uma personagem",myCharacters:"As minhas personagens",lookup:"Procurar",enterCharacter:"Nome da personagem",realm:"Reino",region:"Região",search:"Procurar",gear:"Equipamento",mythicPlus:"Mítica+",raids:"Raides",achievements:"Proezas",itemLevel:"Nível de item",rating:"Pontuação",bestRuns:"Melhores corridas",noRuns:"Sem corridas esta época",guild:"Guilda",share:"Partilhar",shareCode:"Código",createCode:"Criar código",viewCode:"Ver um código",enterCode:"Inserir código",myCodes:"Os meus códigos",copied:"Copiado",settings:"Definições",language:"Idioma",theme:"Tema",themeLight:"Claro",themeDark:"Escuro",themeSystem:"Sistema",signOut:"Sair",loading:"A carregar …",retry:"Tentar de novo",notFound:"Não encontrado",noChars:"Sem personagens. Inicia sessão com Battle.net.",level:"Nível"},
};
let n=0; for(const l of LANGS){ fs.writeFileSync(path.join(OUT,`${l}.json`), JSON.stringify(S[l],null,2)+"\n"); n++; console.log("✓",l); }
console.log(`\n${n} locale files written`);
